"""empty message

Revision ID: 471881f75656
Revises: 47beeadecda7
Create Date: 2014-04-14 13:34:55.518000

"""

# revision identifiers, used by Alembic.
revision = '471881f75656'
down_revision = '47beeadecda7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
